### ISSUE TITLE
Not making it past await

### ISSUE THREAD

**Issue by schmidtc63** [chadly/Geocoding.net#101]
I'm running this in mycontrol.ascx.cs:<br/><br/>
```
private async Task<IEnumerable<Address>> getLongLatAsync()
{
    var geocoder = new GoogleGeocoder{ApiKey = "asdfsafsadfaewrafsfsdf"}; //using my actual key
    IEnumerable<GoogleAddress> addresses = await geocoder.GeocodeAsync("1600 pennsylvania ave washington dc");
    return addresses;
}

```
<br/><br/>
It never makes it past the "await geocoder". No error. It just stops processing. Are there any non-async calls like there used to be?

**Comment by chadly** [comment]
I haven't used webforms in a long time. Does it support async/await? How are you calling this method?

If you want to make it behave non-async, you can do it yourself with:

```c#
IEnumerable<GoogleAddress> addresses = geocoder.GeocodeAsync("1600 pennsylvania ave washington dc").Result;
```
