### ISSUE TITLE
Assemblies not signed with a strong name

### ISSUE THREAD

**Issue by Koopakiller** [chadly/Geocoding.net#103]
At least `Geocoding.Core` and `GeoCoding.Microsoft` does not have a strong assembly name. Tested with the current NuGet-Package (Version 4.0.1). 

Our project assemblies must be signed, so we cannot use your Package...
Can you commit an update?

**Comment by chadly** [comment]
This is intentional. Please use [strong namer](https://github.com/dsplaisted/strongnamer) if you need signed assemblies.

See #75, #84
