### ISSUE TITLE
Add CancellationToken to GeocodeAsync and ReverseGeocodeAsync

### ISSUE THREAD

**Issue by dfyx** [chadly/Geocoding.net#110]
It would be nice to be able to cancel `GeocodeAsync` and `ReverseGeocodeAsync`. As geocoding is mostly IO-bound and `HttpClient` already support cancellation, it should be as simple as accepting a `CancellationToken` and passing it to the web requests.

If you're interested I could implement that today or tomorrow.

**Comment by chadly** [comment]
Yes, that sounds good.

**Comment by dfyx** [comment]
Alright, I got some other work to do so implementing this will take a little longer.
