### ISSUE TITLE
MapQuest requests should include a charset in headers

### ISSUE THREAD

**Issue by vdachev** [chadly/Geocoding.net#137]
Hello,

Today I tested geocoding using the MapQuest implementation and it works pretty fine both for the OSM and commercial API. They seem to be virtually the same.

However, an issue arises when I try to use non-ASCII symbols in the location I provide.

In the `Content-Type` header, `Geocoding.MapQuest` sets `application/json`. As it does not specify an encoding, MapQuest's API seems to assume the request is in ASCII and returns inadequate results.

To avoid this, I think the `Geocoding.MapQuest` should set the `Content-Type` header to `application/json; charset=utf-8`.

**Comment by RodneyRichardson** [comment]
Do you have an example of a unicode search that is failing?
