### ISSUE TITLE
Error when running in .NET 4 only environment

### ISSUE THREAD

**Issue by craigsmitham** [chadly/Geocoding.net#20]
The following exception is thrown: Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'mscorlib'

This StackOverflow post describes a similar error: http://stackoverflow.com/questions/13748055/could-not-load-type-system-runtime-compilerservices-extensionattribute-from-as

This blog post describes the underlying issue: http://www.mattwrock.com/post/2012/02/29/What-you-should-know-about-running-ILMerge-on-Net-45-Beta-assemblies-targeting-Net-40.aspx

**Comment by chadly** [comment]
No more IL merging in v4.0. See the [latest release notes](https://github.com/chadly/Geocoding.net/releases/tag/v4.0.0).
