### ISSUE TITLE
Always explicitly setting Proxy (even to null) prevents the use of the default system proxy.

### ISSUE THREAD

**Issue by joekrill** [chadly/Geocoding.net#30]
The Google and Microsoft providers are explicitly always setting the Proxy on the web request, even if it is `null`. Which makes it cumbersome to use the default system proxy. And it causes the requests to ignore it if you supply this in your .config:

`<system.net>
   <defaultProxy enabled="true" useDefaultCredentials="true" />
</system.net>`

Instead, consider:

```
if(this.Proxy != null) {
  request.Proxy = this.Proxy;
}
```

The MapQuest geocoder does this. The Yahoo Geocoder doesn't seem to support proxies at all. Not only that, the property should really be changed to an `IWebProxy` instead of `WebProxy`. Because even if I manually wanted to set the provider to use the default proxy, `System.Net.WebRequest.DefaultWebProxy` returns the interface (`IWebProxy`) and not the class (`WebProxy`).

**Comment by joekrill** [comment]
Adding reference to issue #31

**Comment by chadly** [comment]
Thanks, I changed them to `IWebProxy` and added it to the `YahooGeocoder` as well.
