### ISSUE TITLE
Improper Handling of Longitude Result Returned from Google Geocoding Service

### ISSUE THREAD

**Issue by edwardfedeli** [chadly/Geocoding.net#34]
In certain cases, the Google geocoding web service returns a longitude result of -180, which does not appear to be valid when parsing the results into the Location object.  I have tried to eliminate the issue by providing custom bounds in the query, but it is not always consistent.

Here is an example with a longitude of -180 from the Google geocoding service:

https://maps.googleapis.com/maps/api/geocode/xml?latlng=26.713422775268555,-80.04793548583984&sensor=false

Here is what I believe to be an issue in the code when attempting to parse the longitude in the Location class:

```C#
public virtual double Longitude
              {
                     get { return longitude; }
                     set
                     {
                           if (value <= -180 || value > 180)
                                  throw new ArgumentOutOfRangeException("Longitude", value, "Value must be between -180 and 180 (inclusive).");
                           if (double.IsNaN(value))
                                  throw new ArgumentException("Longitude must be a valid number.", "Longitude");
 
                           longitude = value;
                     }
              }
```

**Comment by chadly** [comment]
This should be fixed in [v3.3.0](http://www.nuget.org/packages/Geocoding.net/)
