### ISSUE TITLE
In version 3.2.1 with coordinate Longitude = -80.1373170, Latitude = 26.1224390 Value must be between -180 and 180 (inclusive)

### ISSUE THREAD

**Issue by thiagoamarante** [chadly/Geocoding.net#35]
Version = 3.2.1
Parameters = Longitude = -80.1373170, Latitude = 26.1224390
Error:
Value must be between -180 and 180 (inclusive).
Parameter name: Longitude
Actual value was -180.

**Comment by chadly** [comment]
This should be fixed in [v3.3.0](http://www.nuget.org/packages/Geocoding.net/)
