### ISSUE TITLE
PCL version

### ISSUE THREAD

**Issue by ravensorb** [chadly/Geocoding.net#39]
Any plans to port this to be compatible with the PCL?

**Comment by chadly** [comment]
I've never played around with the PCL before, but I do have plans to make it work with .Net Core 5 as mentioned in #41

**Comment by niemyjski** [comment]
I'd really like coreclr support which would also fulfill the requirements of pcl.

**Comment by chadly** [comment]
It now builds against [.Net Standard 1.3](https://docs.microsoft.com/en-us/dotnet/standard/library) in v4.0. See the [latest release notes](https://github.com/chadly/Geocoding.net/releases/tag/v4.0.0).
