### ISSUE TITLE
MapQuest API no longer likes the Expect:application/json header

### ISSUE THREAD

**Issue by joshsacks** [chadly/Geocoding.net#42]
It throws a 417 if that header is included. This header can be safely removed.

**Comment by chadly** [comment]
I haven't looked into it but a quick google search [turned this up](http://stackoverflow.com/a/566847/316108). Could that be the issue and not the `contentType` header?

**Comment by joshsacks** [comment]
No, it's definitely the Expect: application/json. I tried it in Fiddler's composer with everything but that (including the Expect: 100Continue), and it worked fine.

**Comment by chadly** [comment]
Fixed with #43
