### ISSUE TITLE
Geocoding.Google.GoogleGeocodingException

### ISSUE THREAD

**Issue by alanberto** [chadly/Geocoding.net#44]
Hi 
I tried the examples you provided in the main page but I get the exception "Geocoding.Google.GoogleGeocodingException"

What am I doing wrong?

Thnx

Al

**Comment by scottrudy** [comment]
I am having the same problem. I am getting an Access Denied on the key that I just generated.

**Comment by scottrudy** [comment]
I found the issue. I had requested the JavaScript (Browser) key, but I need the server key for GeoCoding. You can get that here: https://developers.google.com/maps/documentation/geocoding/get-api-key

**Comment by chadly** [comment]
Thanks for sharing the fix @scottrudy
