### ISSUE TITLE
Doesn't seem to work with mapquest..

### ISSUE THREAD

**Issue by robdob** [chadly/Geocoding.net#45]
Hi,
I'm doing the following...
geocoder = new Geocoding.MapQuest.MapQuestGeocoder("Foy.......") { UseOSM = true };
IEnumerable<Geocoding.Address> addresses = geocoder.Geocode(sAddressLine );

this works with both google and bing, but throws an exception when using MapQuest
oException = {"[POST] http://open.mapquestapi.com/geocoding/v1/address?key=Foy............EXPECTATION_FAILED | "}

do you have any suggestions,?  thank you and great api... :)

**Comment by Obi1-Cannabis** [comment]
Same problem here... would love to have some feedback.

**Comment by chadly** [comment]
See #48
