### ISSUE TITLE
Async API

### ISSUE THREAD

**Issue by niemyjski** [chadly/Geocoding.net#47]
The world we live in today is 100% async. I think that the whole api should be async and those who are needing non async can use wrappers around there code to make it sync.

This would also make the api more consistent because you can't currently do an async reverse geocode..

**Comment by chadly** [comment]
Yes, I agree. I am planning a v4.0 to be released alongside .net core at which point I think introducing this API change makes sense.

**Comment by Dexyon** [comment]
How is the progress on the .NET CORE ? I see your feature branch, but it seems a bit out of date..

**Comment by adamhathcock** [comment]
Updated the feature branch in a PR if anyone is interested.

**Comment by mclang** [comment]
Did I understood right: There is `GoogleGeocoder.ReverseGeocodeAsync` -function, but it doesn't work?

I'm trying to use F# Async Workflow to reverse geocode e.g 100 addresses, but the best queries per second I get is around 2.

Is there documentation how to make several parallel requests using Geocoding.net either with Task Parallel Library or or with Async Workflow?

**Comment by chadly** [comment]
this is released in [v4.0](https://github.com/chadly/Geocoding.net/releases/tag/v4.0.0)
