### ISSUE TITLE
When i use Mapquest geocode i got an error.

### ISSUE THREAD

**Issue by tvrajja** [chadly/Geocoding.net#48]
When i use Mapquest geocode i got an error.
In Example.Web
global.asax.cs after GoogleGeocoder i have added the below MapQuestGeocoder
builder.Register(c => new MapQuestGeocoder("KEY") { UseOSM = true }).As<IGeocoder>();

Homecontroller:
var addresses = geoCoder.Geocode(address).ToArray();
return View("Index", addresses);
{"[POST] http://open.mapquestapi.com/geocoding/v1/address?key=MYKEY | EXPECTATION_FAILED | "}

**Comment by spoloha11** [comment]
I encountered the same error.  As a work around, in Mapquest -> MapquestGeocoder.cs, put the following line above the return statement.

`request.ServicePoint.Expect100Continue = false;`

**Comment by chadly** [comment]
Thanks for the workaround @spoloha11. See also #29.

**Comment by chadly** [comment]
Unable to reproduce. See #68.
