### ISSUE TITLE
{"Unable to cast object of type 'System.Collections.Generic.List`1[Geocoding.Microsoft.BingAddress]' to type 'Geocoding.Microsoft.BingAddress[]'."}

### ISSUE THREAD

**Issue by lcrf1975** [chadly/Geocoding.net#53]
I getting this issue when I try to use the instruction below:
string Confidence = ((BingAddress[])addresses)[0].Confidence.ToString();

But works to Google:
string LocationType = ((GoogleAddress[])addresses)[0].LocationType.ToString();

What can I do?

**Comment by chadly** [comment]
```cs
string Confidence = addresses.ToArray()[0].Confidence.ToString();
```

or

```cs
string Confidence = addresses.First().Confidence.ToString();
```
