### ISSUE TITLE
Add support .NET Core

### ISSUE THREAD

**Issue by valeravorobjev** [chadly/Geocoding.net#72]

**Comment by Pinski** [comment]
Any plans on adding this functionality?

**Comment by chadly** [comment]
It now builds against [.Net Standard 1.3](https://docs.microsoft.com/en-us/dotnet/standard/library) in v4.0. See the [latest release notes](https://github.com/chadly/Geocoding.net/releases/tag/v4.0.0).

**Comment by niemyjski** [comment]
@chadly the build seems to be failing and the nuget packages are on 3.6.1. Can you please push an updated 4.0 :)

**Comment by chadly** [comment]
The `Geocoding.net` package has been deprecated in favor of split packages:

```
Install-Package Geocoding.Google
Install-Package Geocoding.MapQuest
Install-Package Geocoding.Microsoft
Install-Package Geocoding.Yahoo
```

See the [updated readme](https://github.com/chadly/Geocoding.net#installation).
