### ISSUE TITLE
v4.0.0 NuGet packages unsigned

### ISSUE THREAD

**Issue by 0657code** [chadly/Geocoding.net#75]
While the v3.6.0 assembly was signed, the new v4.0.0 NuGet assemblies are not signed with a strong name.

**Comment by chadly** [comment]
Yes, this is intentional. Please use [strong namer](https://github.com/dsplaisted/strongnamer) if you need signed assemblies.

**Comment by 0657code** [comment]
Unfortunately that is not an option for me, so I will have to build from source.

**Comment by chadly** [comment]
I'm curious why this is not an option. I know other OSS projects have found success and much happier users with dropping signed assemblies and referring people to [strong namer](https://github.com/dsplaisted/strongnamer).

**Comment by 0657code** [comment]
I am using this for a work project and having something hook into the build process to sign unknown assemblies with our corporate key does not seem like a very good idea.

On a side note, with building from source I am also able to compile the necessary files in a single assembly (Core and Microsoft in my case) and then change to access modifier of Extensions to internal, so I do not have these extension methods (which are of internal nature) available whenever I import Geocoding.Core. I do understand however that you have to make it public to access it from the provider projects, unless you want to deal with InternalsVisibleToAttribute - which might not be supported by StrongNamer, to get back on topic.
