### ISSUE TITLE
Serialization error in Geocoding.Microsoft

### ISSUE THREAD

**Issue by 0657code** [chadly/Geocoding.net#76]
Newtonsoft.Json does not serialize the Resource as a Location type, thus the cast in the ParseResponse-Method fails.

This issue may be present in other Geocoders. It has appeared in a project built from source, incorporating Geocoding.Core and Geocoding.Microsoft. The target framework is .NET 4.6.1.

**Comment by chadly** [comment]
fixed in b9db587db27c4590109c91a57a0729a55d77a903
