### ISSUE TITLE
How to use Accuracy value from Google?

### ISSUE THREAD

**Issue by Mike55555** [chadly/Geocoding.net#86]
Hello all - is there any way to access the Accuracy value that Google returns? I've gone through the properties available through intellisense but can't find anything that looks valuable. (And sorry for raising an issue - I couldn't find a discussion forum anywhere).

**Comment by chadly** [comment]
Are you talking about the [`GoogleAddress.Type`](https://github.com/chadly/Geocoding.net/blob/master/src/Geocoding.Google/GoogleAddress.cs#L16)? It is of type [`GoogleAddressType`](https://github.com/chadly/Geocoding.net/blob/master/src/Geocoding.Google/GoogleAddressType.cs).

**Comment by Mike55555** [comment]
Ah - good one, thanks for that pointer!
