### ISSUE TITLE
Unit test for Bing checks for Canada in first result only

### ISSUE THREAD

**Issue by RyanONeill1970** [chadly/Geocoding.net#95]
The ApplyUserLocation unit test passes a French location hint to Bing when searching for Montreal.
Bing stupidly returns the results with Canada first, but the other results are for France.

The unit test only checks the first country (Bing does seem to return them in Confidence order which seems broken) so this test fails.

I'd like to fix the test, would a pull request be considered?

The fix can come in the form of;

1. Check if any of the countries are 'France'.
1. Order the results by their proximity to the lat/lng hint and then check the first in the unit test.

Your thoughts?

**Comment by chadly** [comment]
Seems like this was fixed with #96
